name: reddwarf-cv-pro

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build React App
        run: |
          git config --global url."https://github".insteadOf ssh://git@github
          npm install -g pnpm 
          pnpm install
          pnpm run build
        env:
          CI: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}
          username: ${{ secrets.ALIYUN_DOCKER_REPO_USER_NAME }}
          password: ${{ secrets.ALIYUN_DOCKER_REPO_USER_PASSWORD }}
    
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/reddwarf-pro/cv-web:${{ github.sha }} 
        
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: 
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/cv-web cv-web=${{ secrets.ALI_DOCKER_HUB_REGISTRY }}/reddwarf-pro/cv-web:${{ github.sha }} -n reddwarf-pro
    
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0
          command: rollout status deployment/cv-web -n reddwarf-pro
    